name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout webshop
        uses: actions/checkout@v4

      - name: Checkout spring-messenger
        uses: actions/checkout@v4
        with:
          repository: Joajak92/spring-messenger
          path: spring-messenger

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Build and install spring-messenger
        run: mvn -B -f spring-messenger/pom.xml clean install

      - name: Build webshop
        run: mvn -B -f pom.xml clean verify
